services:
  ts-node-docker:
    container_name: ts-node-docker
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - APP_PORT=${APP_PORT:4321}
    volumes:
      - ./app:/home/node/app
      - ./app/nodemon.json:/home/node/app/nodemon.json
    expose:
      - '${APP_PORT:4321}'
    ports:
      - '${APP_PORT:4321}:4000'
    environment:
      - APP_PORT=${APP_PORT:4321}
    command: npm run dev
