services:
    db:
        image: mysql:latest
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            # https://dev.mysql.com/doc/refman/8.4/en/environment-variables.html
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DEBUG: ${MYSQL_DEBUG}
            MYSQL_HOME: ${MYSQL_HOME}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
            MYSQL_UNIX_PORT: ${MYSQL_UNIX_PORT}
            TZ: ${TZ}
        volumes:
            - ./db:/var/lib/mysql

    php:
        build:
            context: ./php-fpm
            args:
                PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
                PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
                PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
                SYMFONY_CLI_VERSION: 5.11.0
        ports:
            - "${PHP_PORT}:9001"
        volumes:
            - ./container:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "${PHPMYADMIN_PORT}:80"
        restart: always
