services:
  web:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${LARAVEL_PORT:-80}:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - lrvl-dev
    depends_on:
      php-fpm:
        condition: service_started

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
    networks:
      - lrvl-dev
    depends_on:
      postgres:
        condition: service_started

  workspace:
    build:
      context: .
      dockerfile: ./docker/dev/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - lrvl-dev

  postgres:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${LARAVEL_POSTGRES_DB:-app}
      - POSTGRES_USER=${LARAVEL_POSTGRES_USER:-laravel}
      - POSTGRES_PASSWORD=${LARAVEL_POSTGRES_PASSWORD:-secret}
    env_file:
      - .env
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - lrvl-dev

  redis:
    image: redis:alpine
    networks:
      - lrvl-dev

networks:
  lrvl-dev:

volumes:
  postgres-data-dev:
