services:
  gitlab-server:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-server
    ports:
      - '8091:80'
    environment:
      GITLAB_ROOT_EMAIL: "admin@email.com"
      GITLAB_ROOT_PASSWORD: "Abcd@0123456789"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - cicd-net

networks:
  cicd-net:
    driver: bridge

volumes:
  gitlab_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config
  gitlab_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data